### ISSUE TITLE
add pipeline does not automatically give the newest version

### ISSUE THREAD

**Issue by dcdanko** [dcdanko/ModuleUltra#2]

**Comment by dcdanko** [comment]
Can workaround by explicitly declaring the type

**Comment by dcdanko** [comment]
```$ moduleultra add pipeline metasub_cap
Traceback (most recent call last):
  File "/home/dcd3001/miniconda3/bin/moduleultra", line 11, in <module>
    load_entry_point('ModuleUltra', 'console_scripts', 'moduleultra')()
  File "/home/dcd3001/miniconda3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dcd3001/miniconda3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dcd3001/miniconda3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dcd3001/miniconda3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dcd3001/miniconda3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dcd3001/miniconda3/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/pbtech_mounts/homes039/dcd3001/Dev/ModuleUltra/moduleultra/cli/cli.py", line 50, in addPipeline
    repo.addPipeline(name, version=version, modify=modify)
  File "/pbtech_mounts/homes039/dcd3001/Dev/ModuleUltra/moduleultra/module_ultra_repo.py", line 47, in addPipeline
    version=version)
  File "/pbtech_mounts/homes039/dcd3001/Dev/ModuleUltra/moduleultra/module_ultra_config.py", line 46, in getPipelineDefinition
    version = getHighestVersion(self.installedPipes[pipelineName])
  File "/pbtech_mounts/homes039/dcd3001/Dev/ModuleUltra/moduleultra/utils.py", line 57, in getHighestVersion
    if nums[0] > nums[1]:
IndexError: list index out of range```
